name: Quality
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - 'testcoveralls/**'
      - 'go.mod'
jobs:
  test:
    name: testcoveralls
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - name: Check out code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          go mod download
      - name: Run Unit tests
        run: |
          go test -race -covermode atomic -coverprofile=coverage ./testcoveralls/...
      - name: Install goveralls
        run: go install github.com/mattn/goveralls@latest
      - name: Send coverage
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_PARALLEL: true
        run: goveralls -coverprofile=coverage -service=github -flagname="adder"
  finish:
    runs-on: ubuntu-latest
    name: finish parallel build
    needs: test
    steps:
      - name: Tell Coveralls that the parallel build is finished
        run: |
          curl -k \
              https://coveralls.io/webhook?repo_token=$COVERALLS_REPO_TOKEN \
              -d "payload[build_num]=$GITHUB_SHA&payload[status]=done"
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
#      - name: Convert coverage to lcov
#        uses: jandelgado/gcov2lcov-action@v1.0.2
#        with:
#          infile: coverage.out
#          outfile: coverage.lcov
#      - name: Coveralls
#        uses: coverallsapp/github-action@master
#        with:
#          github-token: ${{ secrets.GITHUB_TOKEN }}
#          path-to-lcov: coverage.lcov