name: Quality
on:
  push:
    branches:
      - avinash/test-monorepo
  pull_request:
    paths:
      - 'testcoveralls/**'
      - 'go.mod'
      - '.github/workflows/**'
jobs:
  test:
    name: testcoveralls
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - name: Check out code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          go mod download
      - name: Run Unit tests
        run: |
          go test -race -covermode atomic -coverprofile=coverage ./testcoveralls/...
#      - name: Install goveralls
#        run: go install github.com/mattn/goveralls@latest
#      - name: Send coverage
#        env:
#          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          COVERALLS_PARALLEL: true
#        run: goveralls -coverprofile=coverage -service=github -flagname="adder"
#      - name: Convert coverage to lcov
#        uses: jandelgado/gcov2lcov-action@v1.0.2
#        with:
#          infile: coverage.out
#          outfile: coverage.lcov
      - name: Coveralls
        run: |
          go install github.com/mattn/goveralls@latest
          goveralls -coverprofile=coverage -service=github
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_FLAG_NAME: 'testcoveralls'
          COVERALLS_PARALLEL: true
          COVERALLS_SERVICE_JOB_ID: ${{ github.sha }}
          COVERALLS_SERVICE_NUMBER: ${{ github.sha }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          compare-ref: avinash/test-monorepo