name: Quality
on:
  push:
    branches:
      - avinash/test-monorepo
  pull_request:
    paths:
      - 'mutli/**'
      - 'go.mod'
jobs:
  test:
    name: multi
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - name: Check out code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          go mod download
      - name: Run Unit tests
        run: |
          go install github.com/jandelgado/gcov2lcov@latest
          go test -race -covermode atomic -coverprofile=coverage.out ./mutli/...
          gcov2lcov -infile=coverage.out -outfile=coverage.lcov
      - name: Coveralls
        uses: coverallsapp/github-action@v2
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_FLAG_NAME: 'multi'
          COVERALLS_PARALLEL: true
          COVERALLS_SERVICE_JOB_ID: ${{ github.sha }}
          COVERALLS_SERVICE_NUMBER: ${{ github.sha }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file: ./coverage.lcov
          compare-ref: avinash/test-compare-ref
